### ISSUE TITLE
Stringhe in spagnolo

### ISSUE THREAD

**Issue by edmondo** [edmondo/wasteland2#12]
Queste righe sono in spagnolo, da tradurre in italiano:
- 1707 : Bien. Entonces, de cuando en cuando mientras patrullan  (...) (CORRETTA)
- 1761 : Los una vez claros ojos dentro de la pantalla  (...) (CORRETTA)

**Comment by DoNotBend** [comment]
1761 - è stata corretta!
1707 - corretta anche questa!

**Comment by edmondo** [comment]
Muchas Gracias, Olé! :-)
Chiudo il bug visto che l'hai risolto.
