### ISSUE TITLE
po' o pò

### ISSUE THREAD

**Issue by edmondo** [edmondo/wasteland2#16]
Stavo dando un'occhiata ai vari cambiamenti nelle stringe degli ultimi giorni e vedo un sacco di po' che sono stati riscritti in pò.

Sono convinto che la forma corretta sia po', con l'apostrofo. La treccani sembra concordare con me:
http://www.treccani.it/enciclopedia/un-po-o-un-po_(La_grammatica_italiana)/

O c'è un motivo particolare per scrivere pò che non conosco?

**Comment by DoNotBend** [comment]
Ho notato la stessa cosa pensavo di aver visto male ma se confermi anche tu vuol dire che qualcuno ha fatto la sostituziona ma vabbè succede, non c'è problema si può sempre rimediare :) edmondo, puoi fare un search e sostituire tutti i pò con po' quando hai tempo? O è un problema il fatto che potrebbe presentarsi in "parole complete" che hanno "pò" come finale? (come mi hai fatto notare con ranger)

Eventualmente vogliamo anche riaprire il topic con le forme corrette? Per le occhiate veloci, just in case.

**Comment by edmondo** [comment]
Sì, stasera correggo i vari pò in po'. Non è grave e c'impiego solo un paio di minuti per farlo.

Il modo più semplice è fare un search and replace della stringa " pò " con " po' " con uno spazio prima e dopo la parola, così escludi tutte le substring del tipo scappò.
Inoltre è importante farlo con "Case Matching" settato, per evitare che un ipotetico " Pò " scritto in maiuscolo diventi " po' " in minuscolo.

**Comment by edmondo** [comment]
Corretto tutti i pò con po'. Chiudo il bug.
