### ISSUE TITLE
Steam Achievements.

### ISSUE THREAD

**Issue by Zanminator** [edmondo/wasteland2#18]
Abbiamo gli Steam Achievements da tradurre. Una volta consegnati non potranno più essere modificati. Ho messo in maiuscolo il nome dell'achievement e sotto la rispettiva descrizione.

PERSONA NON GRATA
Get Ranger Team Delta sent after you
A NIGHT TO REMEMBER
Get an STD
WHAT DOES THIS BUTTON DO?
Set off the nuke in Ranger Citadel before going to LA
THEY WALK AMONG US
Have a party member turn into a pod person
PEACE ON THE RAILS
Make peace between the Atchisons and Topekans
WASTELAND JUSTICE
Witness Angela kill Samuel Haas
TASTY!
Give the Night Terror 20 pieces of candy
EMBRACE THE GLOW
Send the nuke to the Mad Monks
FIGHT FIRE WITH FIRE
Send the nuke to the DBM
RED WIRE, BLUE WIRE
Disarm the nuke
FATEFUL REUNION
Meet Ralphy's dad with Ralphy in tow
A GENTLE HEART
Save Binh from Tinker
UNDER OLD MANAGEMENT
Restore Rodia's mayor to office
HELL BENT FOR LEATHER
Help Chris Van Graas Jr. become mayor of Rodia
SELF ACTUALIZED
Put the Robbinsons in power in Angel Oracle
HOW RUDE
Help Mr. Manners eliminate Tori Robbinson's plot
CIVILIZED
Convince the Mannerites to stop eating people
DIVINE RETRIBUTION
Help Retribution Jones take over Hollywood
RELIGIOUS PERSECUTION
Kill all of the God's Militia leadership
SINNERS AND SAINTS
Make peace between Hollywood and the Bastion
TOO MUCH TIME ON YER HANDS
Dig up all the holes at Redondo Beach
I AM LEGEND
Complete Matthias' quest to kill in LA
BLAST FROM THE PAST
Learn Combat Shooting
POP IDOL
Find The Fin's poster
EZEKIEL 18:20
Intervene in a God's Militia execution
CAT BURGLAR
Steal the Golden Spike from Kekkahbah's fortress without being detected
NOT MONKEYING AROUND
Complete the game with a Ranger dressed in a gorilla costume
KNOW YOUR ROOTS
Find a Wasteland 1 disk
SINISTER LEGACY
Use the code from Finster's head to get into Darwin's underground complex
SWEET, SWEET SQUEEZINS
Scotchmo steals 5 bottles of Snake Squeezins from you
SCAVENGER
Find all of the world map caches
CALL OF THE WILD
Use Animal Whisperer to charm 20 animals
LOCKED AND LOADED
Apply 20 weapon mods
MOO, I SAY
Tip 5 cows
GOAT SIMULATOR
Get 3 goats following the party at once
SON OF A MOTHERLESS GOAT
Outfit 3 rangers in the amigos hat, jacket, and pants
BETTER LEFT BURIED
Find the hidden cache of extraterrestrial cartridges
RELICS OF A BYGONE AGE
Find all hidden shrines in the game
SKIN 'O YER TEETH
Survive a combat encounter with only 1 party member standing
OOPS
Accidentally kill a party member with friendly fire
WASTELAND HISTORIAN
Read every lore entry in the game
ELBOW GREASE
Repair 10 locks or safes using Mechanical Repair
WEST OF EDEN
Go to Los Angeles
BACK WHERE IT ALL BEGAN
Return to Arizona
A GENERAL AND A GENTLEMAN
Allow Vargas to detonate the nuke
PUSHED THE BUTTON
You foolishly pushed the button in the Hollywood Sewers

**Comment by Zanminator** [comment]
Ok primo tentativo:

PERSONA NON GRADITA
Fatti mettere la Squadra Ranger Delta alle calcagna
UNA NOTTE INDIMENTICABILE
Contrai una malattia venerea
A COSA SERVE QUESTO PULSANTE?
Fai detonare la bomba atomica nella Cittadella prima di andare a Los Angeles
SONO TRA NOI
Lascia che un membro del tuo gruppo si trasformi in un uomo baccello
LA PACE SUI BINARI
Instaura la pace tra gli Atchison e i Topekan
LA GIUSTIZIA DELLE LANDE
Guarda Angela mentre uccide Samuel Haas
CHE BUONE!
Dai 20 caramelle al Terrore Notturno
ABBRACCIA IL BAGLIORE
Invia la testata nucleare ai Monaci Matti
COMBATTI IL FUOCO CON IL FUOCO
Invia la testata nucleare alla MCD
FILO ROSSO, FILO BLU
Disarma la testata nucleare
RIUNIONE FATIDICA
Incontra il padre di Ralphy con Ralphy al seguito
UN CUORE DELICATO
Salva Binh da Tinker
SOTTO LA VECCHIA DIREZIONE
Rimetti in carica il sindaco di Rodia
L'INFERNO SI INCHINA DINNANZI AL CUOIO
Aiuta Chris Van Graas Jr. a diventare sindaco di Rodia
AUTOREALIZZATO
Metti i Robbinson al comando dell'Oracolo dell'Angelo
CHE MALEDUCAZIONE
Aiuta il Sig. Manners a sventare il complotto di Tori
CIVILIZZATO
Convinci i Manieriti a smetterla di praticare il cannibalismo
PUNIZIONE DIVINA
Aiuta Retribution Jones a conquistare Hollywood
PERSECUZIONE RELIGIOSA
Uccidi tutti i capi della Milizia di Dio
SANTI E PECCATORI
Instaura la pace tra il Bastione e Hollywood
TANTO TEMPO DA PERDERE
Scava tutte le buche a Redondo Beach
IO SONO LEGGENDA
Porta a termine tutti gli omicidi commissionati da Matthias a Los Angeles
RITORNO AL PASSATO
Impara l'abilità Tiro Operativo
IDOLO POP
Trova il poster di Fin
EZECHIELE 18:20
Intervieni in una esecuzione della Milizia di Dio
LADRO FELINO
Ruba il Chiodo d'Oro dalla fortezza di Kekkahbah senza farti scoprire
SMETTILA DI SCIMMIOTTARMI
Completa il gioco con un Ranger travestito da gorilla
CONOSCI LE TUE RADICI
Trova un dischetto di Wasteland 1
UNA SINISTRA EREDITÀ
Usa il codice preso dalla testa di Finster per entrare nel complesso sotterraneo di Darwin
CARE, DOLCI SPREMUTE
Fatti rubare 5 bottiglie di Spremuta di Serpente da Scotchmo
SCIACALLO
Trova tutte le casse nella mappa globale
QUANDO LA NATURA CHIAMA
Usa l'abilità Amico degli Animali per catturare l'attenzione di 20 animali
CARICO E PRONTO A SPARARE
Monta 20 modifiche per le armi
HO DETTO MUUU
Stendi 5 mucche
GOAT SIMULATOR
Fai seguire il tuo gruppo da 3 capre contemporaneamente
FIGLIO DI UNA CAPRA SENZA PADRE (è una citazione del film "I tre amigos")
Fai indossare a 3 Ranger il cappello, la giacca e i pantaloni dei los amigos
ERA MEGLIO LASCIARLE SOTTO TERRA
Trova il nascondiglio segreto che contiene le cartucce dell'Extraterrestre
RELIQUIE DI UN'EPOCA REMOTA
Trova tutti gli altari nascosti nel gioco
PER IL ROTTO DELLA CUFFIA (l'originale è una citazione della bibbia, ma non rende in italiano)
Sopravvivi a un combattimento con un solo membro del gruppo
OPS
Uccidi per sbaglio un membro del gruppo con il fuoco amico
STORICO DELLE LANDE DESOLATE
Leggi tutti i documenti presenti nel gioco
OLIO DI GOMITO
Ripara 10 serrature o casseforti usando l'abilità Meccanico
A OVEST DELL'EDEN
Vai a Los Angeles
DI NUOVO DOVE TUTTO HA AVUTO INIZIO
Ritorna in Arizona
GENERALE E GENTILUOMO
Permetti a Vargas di far detonare la bomba
HAI PREMUTO IL PULSANTE
Hai scioccamente premuto il pulsante che si trova nelle Fogne di Hollywood

**Comment by vandalazzo** [comment]
TROPPO TEMPO DA SPRECARE
Scova tutte le buche a Redondo Beach

io sarei per:
TANTO TEMPO DA PERDERE
Scava tutte le buche a Redondo Beach

sulle due "fai fare la pace..." sarei per un "instaura la pace fra..."

**Comment by Zanminator** [comment]
Traduzioni aggiornate.

Per "MOO, I SAY: Tip 5 cows" ho trovato questo: http://steamcommunity.com/app/240760/discussions/0/613941122600886721/

Potrebbe andare bene: "HO DETTO MUUU: Stendi 5 mucche"?

**Comment by DoNotBend** [comment]
Per me va bene "HO DETTO MUUU: Stendi 5 mucche". Confermo che cow tipping è un "gioco" (stupido) che si fa nelle campagne americane, praticamente è spingere una mucca da un lato per farla cadere a terra, alcuni ragazzi giurano di esserci riusciti ma è fisicamente impossibile farlo da soli. La citano ogni tanto come attività (sempre stupida) nei film/telefilm.

STD oltre ad essere una malattia venerea potrebbe essere la sigla di un'arma o altro?

"MA A COSA SERVE QUESTO PULSANTE?", toglierei il "ma".

"Van Graas" è ancora da decidere come scrivere.

"Retribution Jones", dobbiamo ancora vedere se tradurlo.

Ne ho controllate 1/3, continuo in giornata.

**Comment by Zanminator** [comment]
@DoNotBend STD sta per Sexually Transmissed Disease.

"Van Graas" è scritto così nella versione inglese.

"Retribution Jones" (e i vari Ascention McDade, Malediction Mayweather, Sanctity White...) non li tradurrei perché sono nomi di persone.

**Comment by DoNotBend** [comment]
Intendevo se dentro il gioco STD è la sigla di qualche cosa, il nome di un'arma o altro, se c'è un doppio gioco nella frase che significa sia malattia venerea che il nome di un oggetto. È un po' strano come achievement se vuol dire soltanto essere andati a prostitute :-\

"Van Graas", hai ragione! Mi sono sbagliata con "Chris VanOverbake"! VanOverbake è quello da decidere, non s'è capito se hanno fatto un errore da inXile oppure è voluto, prima era stato messo in italiano come "Chris van Overbake" (mentre in inglese era scritto sempre come VanOverbake) perché il van olandese generalmente è staccato e minuscolo, solo in pochissimi casi maiuscolo. Meglio se chiediamo a inXile se è voluto averlo messo così?

"Retribution" mi ricordavo fosse il soprannome di Jones non il suo nome. Sì, allora non va tradotto. Idem per compagnia bella.

**Comment by Zanminator** [comment]
Nel gioco non c'è niente che si chiama STD, quindi si tratta quasi sicuramente di una malattia. Infatti c'è uno stato che si chiama "Polydactyl Siphillitis".

Van Graas va scritto con la maiuscola, visto che non è olandese, ma americano: http://it.wikipedia.org/wiki/Van_(preposizione) "In alcune versioni anglicizzate dei nomi olandesi (ad esempio, Dick Van Dyke, Martin Van Buren), o nel caso in cui la parola non è di origine olandese, come nei nomi vietnamiti (Duong Van Minh, Nguyen Van Thieu), la "V" è maiuscola."

Tra l'altro, prima Van Graas e VanOverbake erano scritti come "van Graas" e "van Overbake", ma poi sono stati corretti nelle forme attuali (se guardi nelle keyword sono rimasti uguali)

Se non ci sono altri dubbi posso mandargli la lista.

**Comment by edmondo** [comment]
Per questo:
CHE BUONO!
Dai 20 caramelle al Terrore Notturno

È un dettaglio non molto importante, ma non andrebbe meglio CHE BUONE! visto che si parla di caramelle?

**Comment by Zanminator** [comment]
HELL BENT FOR LEATHER, è un modo di dire che significa fare le cose velocemente, in questo caso è usato come gioco di parole: http://idioms.thefreedictionary.com/hell-bent+for+leather

Ho chiesto a Ragfox e mi ha scritto questo: "Hell-Bent-for-leather" significa "Il più rapidamente possibile" o, meglio ancora, "A velocità folle", "A rotta di collo".
Gioco di parole intraducibile, potete pensare a qualcosa del tipo "A rotta di cuoio", "O Rodia o morte", "O cuoio o morte" e cose del genere. L'inferno c'entra poco :)"

Un'alternativa che avevo pensato io è: "DURO COME IL CUOIO".

Per NOT MONKEYING AROUND, preferite SMETTILA DI SCIMMIOTTARMI oppure MI È SALITA LA SCIMMIA oppure MI È VENUTA LA SCIMMIA?

**Comment by edmondo** [comment]
Hm... piuttosto difficile.

Se vuoi rimanere sul tema velocità e inferno, qualcosa come "A ritmo infernale" potrebbe funzionare. Se ho capito bene Chris è un Bastardo di Cuoio. Hm, "IL RITMO INFERNALE DEI BASTARDI"?

Monkeying: "RANGER SENZA SCIMMIOTTAMENTI" ?

**Comment by Zanminator** [comment]
@edmondo Per HELL BENT FOR LEATHER, meglio lasciar perdere il doppio senso della versione originale, visto che in italiano non viene bene, un po' come per NOT MONKEYING AROUND. Per questo avevo pensato a DURO COME IL CUOIO, visto che Chris quando diventa sindaco di Rodia diventa automaticamente anche il capo dei Leather Jerks, ma se qualcuno riesce a essere più creativo, tanto meglio.

Pensavo di consegnare la traduzione questa sera, visto che tutti gli altri traduttori l'hanno già consegnata da una settimana.

**Comment by edmondo** [comment]
@Zanminator Sono d'accordo con te. Vai con "DURO COME Il CUOIO". Per Monkeying preferisco la variante "SMETTILA DI SCIMMIOTTARMI".

Un dettaglio minimo: PERSONA NON GRADITA personalmente l'avrei lasciato PERSONA NON GRATA. Da noi è un'espressione che viene usata più spesso rispetto a gradita. Non è comunque importante e lascio a voi la decisione. Per me  la lista si può consegnare così com'è ora.

**Comment by Zanminator** [comment]
@edmondo Per PERSONA NON GRATA, ti scrivo quello che mi aveva detto Ragfox: "Lasciare "Persona non grata" in latino va bene, ma non disdegnerei l'idea di mettere "Persona non gradita" in italiano. In inglese "Persona non grata" è subito identificata come espressione latina, ma, in italiano, se chi legge non sa che la frase è in latino, essa potrebbe "suonare male", visto che "grata" e "gradita" sono due parole diverse (parlo dell'italiano, non della traduzione dal latino). Es. "Ti sono grato"È difficile spiegare il mio ragionamento :D"

**Comment by DoNotBend** [comment]
Achievements aggiornati sulla pagina steam :)
