### ISSUE TITLE
Sa-sa... Prova 1-2-3...

### ISSUE THREAD

**Issue by DoNotBend** [edmondo/wasteland2#2]
Sopra la panca la capra canta sotto la panca la capra crepa.
Trentatré trentini entrarono a Trento, tutti e trentatré trotterellando.
Se l'arcivescovo di Costantinopoli si disarcivescoviscostantinopolizzasse, tu ti disarcivescoviscostantinopolizzeresti come si è disarcivescoviscostantinopolizzato l'arcivescovo di Costantinopoli?

**Comment by edmondo** [comment]
Test Screenshot
![2014-09-21_00001](https://cloud.githubusercontent.com/assets/1729650/4349804/59ba2d80-41c6-11e4-9841-7e2679241a4a.jpg)
