### ISSUE TITLE
(edmondo) Appunti, TODO, DONE

### ISSUE THREAD

**Issue by edmondo** [edmondo/wasteland2#9]
# Appunti personali

(link a getlocation probabilemente non più funzionanti)
## Revisionato

HCC - DONE
Ma Brown - DONE
sledgehammer - DONE
HSP - DONE
Schwag - DONE
exalted -> eccelsi - DONE
high ground -> Dispensario di Sogni - DONE
Griffith Park - DONE
biblie  - DONE
James King - DONE
decrittatore -> codificatore - DONE
denture paste -> adesivo per dentiere - DONE
fungicide -> fungicida - DONE
finchè - DONE
Fatfingers -> Ditagrasse - DONE
Mark of Titan -> Marchio di Titan - DONE
Mark Bearer -> Portatore del Marchio - DONE
Mushroom Cloud -> Fungo Atomico - DONE
DBM -> MCD - DONE
Outpost One -> Avanposto Uno - DONE
bacello/i -> baccello/i - DONE
Great Glow - Bagliore Glorioso - DONE
Mercaptan -> Mercaptain - DONE
Mushroom Caves -> Grotte Fungaie - DONE
perchè/perche' -> perché - DONE
Sansone -> Samson - DONE
Sampson -> Samson - DONE
`<...> invece di <@...>` - DONE
apostrofi -> accenti - DONE (la maggior parte credo)
## Incaricate altre persone

Rad Suit: Tute Antiradiazioni - DoNotBend
Mr. - Xanthos
## Da controllore

gauntlet -> sfida
sledgehammer -> mazza
pre-war -> prebellico
## Da pensarci sopra

`**cough**  -> **coff**`

Samson's Snack Shoppe

Vulture's Cry

(% ... ) https://www.getlocalization.com/inxle/editor/18984/#5264532

wrath -> ira

chance to hit
chance to evade
Ledger
Watts
melee
pistol packing priest

Priestkiller

Keycard
worker bot
sprayer
party/team
synth
snake squeezins

copperfield:
http://www.getlocalization.com/inxle/editor/18984/#5467392

AoE

workbot

farmer jim

Greek Theater

Ag Center
Desert Ranger

Quest Giver:
http://www.getlocalization.com/inxle/editor/18984/#5464435

TO REV:
https://www.getlocalization.com/inxle/editor/18984/#5381565

**Comment by DoNotBend** [comment]
@edmondo - sbaglio o ora tutti i "Ranger" in eng sono in maiuscolo? Fai tu il trova e sostituisci di Rangers/rangers/ranger in Ranger nella versione ita?

**Comment by edmondo** [comment]
In inglese ci sono 1641 stringhe con ranger(/s) in minuscolo e 1659 con Ranger(/s) in maiuscolo.

In italiano ci sono ancora un solo rangers, un solo Rangers e svariati ranger minuscoli. Correggo tutto in Ranger.
